import Sidebar from "@/components/Sidebar";
import "./globals.css";
import { Quicksand } from "next/font/google";
import Topbar from "@/components/Topbar";
import Navbar from "@/components/Navbar";

const quicksand = Quicksand({ subsets: ["vietnamese"] });

export const metadata = {
  title: "D2Y OFFICIAL",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={quicksand.className}>{children}</body>
    </html>
  );
}
